### ISSUE TITLE
The jump does not work properly

### ISSUE THREAD

**Issue by Pab450** [farbodgame/chrome-dinosaur#1]
When I press the space bar on my computer keyboard for a long time, the dinosaur jumps correctly but does not fall to the ground directly after that. This bug is very annoying.

**Comment by Domosed-gamin** [comment]
yes, jump is broken

**Comment by ChristianBar** [comment]
I tried to fix it in my fork, you can have a look if you want ;)

**Comment by farbodahm** [comment]
@ChristianBar Thanks man; Please feel free to open up a pull request if you think that's solved.
